name: Build/release

on:
  push:
    tags:
      - 'v*'
permissions: {}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        # os: [macos-latest, windows-latest]
        arch: [x64, arm64]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      # - name: Build
      #   run: bun run build
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v4
      #   with:
      #     version: 9

      # - name: Install dependencies
      #   run: pnpm install

      # - name: Build
      #   run: pnpm run build

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
